title: Tech-Box
email: hjryoo31@gmail.com
description: Welcome to Tech-Box Jekyll Ver.
baseurl: ''
url: ''
twitter_username: 'null'
github_username: hjryoo
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-paginate-v2
'gem ''jekyll-admin'', group': ':jekyll_plugins'
gems:
  - jekyll-paginate-v2
permalink: '/:year/:month/'
pagination:
  enabled: true
  per_page: 12
  sort_reverse: true
  sort_field: date
  title: ':title'
  trail:
    before: 2
    after: 2
